### PR TITLE
Russian translations

### PR DESCRIPTION
**Pull request by Felix14-v2**

### CODE REVIEW

**Comment by Sjouwer** [comment]
Thanks a lot for your contribution

**Comment by Felix14-v2** [comment]
And you for your great mod!

**Comment by Sjouwer** [comment]
You're welcome, I'm happy to see you enjoy the mod
I just published a 1.17 version with the translation added, I will also publish a new 1.18 beta version once the new snapshot is out

**Comment by Sjouwer** [comment]
Hey Felix, I'm not quite sure how else to reach you, but I was wondering if you would be willing to update the translations. I've added a new config option for this mod. I would like to publish a new release soon and would really appreciate it if you'd be able to update it

**Comment by Felix14-v2** [comment]
I'm sorry I didn't do this earlier – I usually track the new translation lines myself, but lately I haven't had enough time for this. Thanks for letting me know, wait for a while.

**Pull request merged**
