### PR TITLE
Fix and update ru_ru.json

### PR DESCRIPTION
**Pull request by Felix14-v2**
- Fixed json syntax broken in the previous PR (@FurnyGo, be more careful with it, it is necessary to test the translation ingame)
- Fixed inconsistency of the new translation with the official Minecraft localization
- Improved some new translations by FurnyGo, fixed some grammatical mistakes
- Improved old translation (just the same meaning but with better sounding and shortened formulations)
- Added translations for ModMenu summary and description

## Important
The names of the paintings won't be translated due to Mojang's decision (they updated their [glossary](https://docs.google.com/spreadsheets/d/1xxDvR2MrPUaxXwNfn-oJX-fBerEsZkfo/)), so i would recommend you just to hardcode their names and remove them from the translation files to avoid unintentional inconsistency
image

### CODE REVIEW

**Comment by Sjouwer** [comment]
Thanks a lot!
Also, my bad, I should have checked if the json syntax was valid.
I'll make sure to do that in the future.

**Comment by Sjouwer** [comment]
Oh and I'll also take a look at the painting names, I saw they added them in the creative menu in the latest 1.19.4 snapshot, so I'll see if I can use those when picking paintings, so the name and artist will already be correct

**Comment by Sjouwer** [comment]
Painting names redone :)
https://github.com/Sjouwer/pick-block-pro/commit/38a7dc46dbc14d0e9bec0b1afa8576862f99e129

**Comment by Felix14-v2** [comment]
> Painting names redone :) [38a7dc4](https://github.com/Sjouwer/pick-block-pro/commit/38a7dc46dbc14d0e9bec0b1afa8576862f99e129)

Noooo... I was too slow to tell you — Mojang has changed their policy regarding the translation of the paintings :D
 This happens extremely rarely, but we seem to be lucky. Now the pictures have been removed from the list of untranslatable terms.
Anyway, at the moment there are no officially accepted translations yet, although by the release of 1.19.4 the proofreaders will have to approve them.

**Comment by Sjouwer** [comment]
Ah ty for the update.
Good thing I'm using the new official translation keys for the paintings, so it should all work out fine

**Pull request merged**
